ALTER TABLE "documents" ADD COLUMN IF NOT EXISTS "description" text;
ALTER TABLE "documents" ADD COLUMN IF NOT EXISTS "source_type" text NOT NULL DEFAULT 'INTERNAL';
ALTER TABLE "documents" ADD COLUMN IF NOT EXISTS "file_url" text;
ALTER TABLE "documents" ADD COLUMN IF NOT EXISTS "storage_path" text;
ALTER TABLE "documents" ADD COLUMN IF NOT EXISTS "mime_type" text;
ALTER TABLE "documents" ADD COLUMN IF NOT EXISTS "google_drive_file_id" text;
ALTER TABLE "documents" ADD COLUMN IF NOT EXISTS "google_drive_url" text;
ALTER TABLE "documents" ADD COLUMN IF NOT EXISTS "digital_asset_id" text;
CREATE INDEX IF NOT EXISTS "documents_source_idx" ON "documents" ("source_type");
CREATE INDEX IF NOT EXISTS "documents_asset_idx" ON "documents" ("digital_asset_id");
